// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTeR6U3qmkEiPuLX2vzGbDMGk5PluGua4',
    appId: '1:454706808445:web:de5b9ab2fc650b27435314',
    messagingSenderId: '454706808445',
    projectId: 'psychologistapp-ee783',
    authDomain: 'psychologistapp-ee783.firebaseapp.com',
    storageBucket: 'psychologistapp-ee783.firebasestorage.app',
    measurementId: 'G-TMPCRJRPWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdZGi1_NMHbgWkjnUVWmauDIMwNK-py1M',
    appId: '1:454706808445:android:90dd3a9fa2185081435314',
    messagingSenderId: '454706808445',
    projectId: 'psychologistapp-ee783',
    storageBucket: 'psychologistapp-ee783.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsE8qvd2JoVL0Ug8JvQoBN3N4M5m0Pp3U',
    appId: '1:454706808445:ios:1dc004e970ae3e8d435314',
    messagingSenderId: '454706808445',
    projectId: 'psychologistapp-ee783',
    storageBucket: 'psychologistapp-ee783.firebasestorage.app',
    iosBundleId: 'com.example.psychoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsE8qvd2JoVL0Ug8JvQoBN3N4M5m0Pp3U',
    appId: '1:454706808445:ios:1dc004e970ae3e8d435314',
    messagingSenderId: '454706808445',
    projectId: 'psychologistapp-ee783',
    storageBucket: 'psychologistapp-ee783.firebasestorage.app',
    iosBundleId: 'com.example.psychoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTeR6U3qmkEiPuLX2vzGbDMGk5PluGua4',
    appId: '1:454706808445:web:ffc4baddaf5f560f435314',
    messagingSenderId: '454706808445',
    projectId: 'psychologistapp-ee783',
    authDomain: 'psychologistapp-ee783.firebaseapp.com',
    storageBucket: 'psychologistapp-ee783.firebasestorage.app',
    measurementId: 'G-GJX7GNHYP2',
  );
}
